### ISSUE TITLE
Doesn't work if members are arrays

### ISSUE THREAD

**Issue by rollbear** [Dwarfobserver/AggregatesToTuples#1]
This is a sad result of the rules of the language, but in real life it's probably not a problem. I just wanted to give you a heads-up about this limitation. Example:

```Cpp
struct S
{
  int n;
  int v[32];
};
```

The type above can be initialized with 2 int values :-(

```Cpp
S s{1,2};
```

This does obviously not play nicely with the deduction.

The solution is to not use C-style arrays, but use `std::array<>` instead.

**Comment by rollbear** [comment]
And now I read enough to see that you already covered that. My bad. Sorry for the noise.

**Comment by Dwarfobserver** [comment]
No problem !
